spring:  application:    name: auth-service  mvc:    view:      prefix: /WEB-INF/jsp/      suffix: .jsp  datasource:    username: root    password: MySQL123$$    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://localhost:3306/TicketDB  jpa:    hibernate:      ddl-auto: updateserver:      
  port: 8001
#eureka:#  client:#    service-url: 
#      default-zone: http://localhost:8000/eureka